[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
Subspace_MESE = "03ee4b65-1735-4169-82da-5df6ad43f66c"
