[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
InteractiveCodeSearch = "54eb57ff-b09b-5185-b2f4-7a93509e494f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MRIBase = "f7771a9a-6e57-4e71-863b-6e4b6a2f17df"
MRIFiles = "5a6f062f-bf45-497d-b654-ad17aae2a530"
MRIReco = "bdf86e05-2d2b-5731-a332-f3fe1f9e047f"
Metrics = "cb9f3049-315b-4f05-b90c-a8adaec4da78"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SEQ_BRUKER_a_MP2RAGE_CS_360 = "4ba9dd0f-9419-4edc-b963-b8b02e27d02f"
